// we are getting contry name 
// we have to count total number of states and districts 
    // -- we can get by aggregae fun. and put that value using wrapper class 
// if we inserting new state so count no. of state and same as count district 
// if we  delete or update it will update that state and district field as sync.


public with sharing class CountryTriggerHandler {

    public static void dataManipulation(Map<Id, Country__c> oldMap, List<Country__c> newList) {


    } // method dataManipulation
} // main


